name: Deploy to server

on:
  workflow_dispatch:
    inputs:
      version:
        description: version of the docker image

jobs:
  scp_transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: NPM instal
        run: | 
          cd frontend
          npm install
          npm run build --configuration=production
      - name: SSH into server, remove container, and recreate
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop portfolio
            docker rm portfolio
            docker pull jonasbeans/portfolio:${{ github.event.inputs.version }}
            docker run \
              -v  ./certs:/certs \
              -v ./research/OnderwerpenGeleerd:/mnt/posts/ \
              -p 8080:8080 \
              -e KEYSTORE_PASSWORD=test \
              --name portfolio -d jonasbeans/portfolio:${{ github.event.inputs.version }} \
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./frontend/dist/*"
          target: "/website_files/portfolio_sites_files/portfolio/"
