name: Deploy to server

on:
  workflow_dispatch:
    inputs:
      version:
        description: version of the docker image
      refresh-container:
        type: boolean
        required: true
        description: Build and redeploy docker image
      refresh-frontend:
        required: true
        type: boolean
        description: Build and redeploy frontend

jobs:
  scp_transfer:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server, remove container, and recreate
        if: ${{ github.event.inputs.refresh-container }}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop portfolio
            docker rm portfolio
            docker pull jonasbeans/portfolio:${{ github.event.inputs.version }}
            docker run \
              -v  ./certs:/certs \
              -v ./research/OnderwerpenGeleerd:/mnt/posts/ \
              -p 8080:8080 \
              --name portfolio -d jonasbeans/portfolio:${{ github.event.inputs.version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: NPM instal
        if: ${{ github.event.inputs.refresh-frontend }}
        run: |
          cd frontend
          npm install
          npm run build --configuration=production
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        if: ${{ github.event.inputs.refresh-frontend }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          strip_components: 1
          source: "./frontend/dist/portfolio/*"
          target: "/website_files/portfolio_sites_files/portfolio/"
