name: Deploy to server

on:
  workflow_dispatch:
    inputs:
      version:
        default: ''
        description: version of the docker image
      refresh-container:
        type: boolean
        required: true
        description: Build and redeploy docker image
      refresh-frontend:
        required: true
        type: boolean
        description: Build and redeploy frontend

jobs:
  scp_transfer:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server, remove container, and recreate
        if: ${{ github.event.inputs.refresh-container == 'true' }}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sh ~/run/restartDockerContainer.sh ${{ github.event.inputs.version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: NPM instal
        if: ${{ github.event.inputs.refresh-frontend == 'true' }}
        run: |
          cd frontend
          npm install
          npm run build --configuration=production
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        if: ${{ github.event.inputs.refresh-frontend == 'true' }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          strip_components: 3
          source: "./frontend/dist/portfolio/*"
          target: "/website_files/portfolio_sites_files/portfolio/"
      - name: SSH into server reload nginx
        if: ${{ github.event.inputs.refresh-frontend == 'true' }}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo /usr/sbin/service nginx reload
